services:
  app:
    build: .
    container_name: chat-backend
    expose:
      - "8080"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - chat-network

  frontend:
    build:
      context: ../GAI_P1_UI
      dockerfile: Dockerfile
    container_name: chat-frontend
    expose:
      - "3000"
    networks:
      - chat-network

  nginx:
    image: nginx:alpine
    container_name: chat-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - app
      - frontend
    networks:
      - chat-network

  mongodb:
    image: mongo:latest
    container_name: chat-mongodb
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_DATABASE=chat
    volumes:
      - mongodb_data:/data/db
      - ./src/main/resources/db/init-data.js:/docker-entrypoint-initdb.d/init-data.js:ro
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb_data: 