services:
  app:
    build: .
    container_name: chat-backend
    expose:
      - "8080"
    env_file:
      - .env
    networks:
      - chat-network

  frontend:
    build:
      context: ../GAI_P1_UI
      dockerfile: Dockerfile
    container_name: chat-frontend
    expose:
      - "3000"
    env_file:
      - .env
    networks:
      - chat-network

  nginx:
    image: nginx:alpine
    container_name: chat-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
      - frontend
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb_data: 