version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=chat
    volumes:
      - mongodb_data:/data/db
      - ./src/main/resources/db/init-data.js:/docker-entrypoint-initdb.d/init-data.js:ro
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb_data: 