spring:
  application:
    name: chat
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: chat
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
          audiences: ${AUTH0_AUDIENCES}

auth0:
  domain: ${AUTH0_DOMAIN}
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: ${AUTH0_AUDIENCE}

aws:
  s3:
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}

app:
  cors:
    allowed-origins: http://localhost:3000, https://ec2-13-51-161-185.eu-north-1.compute.amazonaws.com

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: WARN 