spring:
  application:
    name: chat
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:chat}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
          audiences: ${AUTH0_AUDIENCES}

auth0:
  domain: ${AUTH0_DOMAIN}
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: ${AUTH0_AUDIENCE}

aws:
  s3:
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: WARN 